### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by ckesurf** [learn-co-curriculum/arrow-functions-discussion-questions#4]
### Canvas Link

https://learning.flatironschool.com/courses/4992/discussion_topics/12999

### Concern

Code is duplicated:

```js
const playMusic = (music) => {
  return "Playing some " + music;
};
playMusic("Jazz"); // "Playing some Jazz"
const playMusic = (music) => {
  return "Playing some " + music;
};
playMusic("Jazz"); // "Playing some Jazz"
```

### Suggested Changes

Just take out the duplicate code, [these lines here](https://github.com/learn-co-curriculum/arrow-functions-discussion-questions/blob/master/README.md?plain=1#L27-L32)

**Comment by lizbur10** [comment]
Hi @ckesurf ! Thanks for bring this to our attention - the redundant example has been removed 💙
