### ISSUE TITLE
the same example appears twice in a row. On purpose?

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/arrow-functions-discussion-questions#6]
### Canvas Link

https://learning.flatironschool.com/courses/5185/discussion_topics/13539?module_item_id=396081

### Concern

Is this example supposed to appear twice? The two entries seem identical and it doesn't seem valuable for people to examine for differences/similarities for identifying they are the same thing. UNLESS: people should be on the lookout for duplicates entering the codebase, and recognizing such is a skill.(?)

```
const playMusic = (music) => {
  return "Playing some " + music;
};
playMusic("Jazz"); // "Playing some Jazz"

const playMusic = (music) => {
  return "Playing some " + music;
};
playMusic("Jazz"); // "Playing some Jazz"
```

### Suggested Changes

remove one of the two identical examples. Or maybe the second instance was supposed to have some slight difference?

**Comment by professor-ben** [comment]
Hi Brigham,

I'm having trouble finding repeated code. Some examples here use implicit returns, I know. You certainly don't need to memorize 100% of the nuances to each example, just understand that there are a number of valid syntaxes in JavaScript.

Thank you,
Ben
