### ISSUE TITLE
Discrepancies between markdown and Canvas

### ISSUE THREAD

**Issue by lantzbuilds** [learn-co-curriculum/arrow-functions-discussion-questions#7]
### Canvas Link

https://learning.flatironschool.com/courses/5220/discussion_topics/14199

### Concern

The Canvas page for this DQ does not display the same as the markdown of the README.  On Canvas, we see:
```
const playMusic = (music) => "Playing some " + music;
playMusic("Jazz"); // "Playing some Jazz"

const playMusic = (music) => "Playing some " + music;
playMusic("Jazz"); // "Playing some Jazz"
```
but the markdown correctly has: 
```
const playMusic = (music) => "Playing some " + music;
playMusic("Jazz"); // "Playing some Jazz"

const playMusic = music => "Playing some " + music;
playMusic("Jazz"); // "Playing some Jazz"
```
omitting parentheses around the parameter.

There are also 9 function examples on the Canvas page compared to 8 on the markdown.

### Suggested Changes

Is the Canvas page reading from an older source for it's markdown, but the Github link comes to this repo?

**Comment by lizbur10** [comment]
Thanks for catching this @betalantz - the Canvas blueprint did not get updated after the last edits. It has now been fixed.
